version: 0.0
os: linux
files:
  - source: source
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: PreInstall.sh
      timeout: 180
  AfterInstall:
    - location: PostInstall.sh
      timeout: 180
